
[pxccluster]
activeFailover = 1
checkTimeOut = 600
debug = 1
development = false
developmentTime = 2000
logDir = "/opt/results/logs"
logLevel = "info"
mainSegment = 1
maxNumWriters = 1
OS = "na"
retryDown = 2
retryUp = 1
singlePrimary = true
writerIsReader = 1
cluster_id=1



[proxysql]
port = 6032
host = "192.168.4.191"
user = "cluster1"
password = "clusterpass"
clustered = false
initialize = true


[global]
debug = true
logLevel = "debug"
logTarget = "stdout" #stdout | file
logFile = "/Users/marcotusa/work/temp/pscheduler.log"
development = true
devInterval = 2000
performance = true
