
[pxccluster]
activeFailover = 1
checkTimeOut = 600
debug = 1
mainSegment = 1
clusterId=1
sslClient = "client-cert.pem"
sslKey = "client-key.pem"
sslCa = "ca.pem"
sslCertificate_path = "/Users/marcotusa/work/temp/ssl_test"

[proxysql]
port = 6032
host = "192.168.4.191"
user = "cluster1"
password = "clusterpass"
clustered = false
initialize = true


[global]
debug = true
logLevel = "debug"
logTarget = "stdout" #stdout | file
logFile = "/Users/marcotusa/work/temp/pscheduler.log"
development = true
devInterval = 2000
performance = true
OS = "na"
